### ISSUE TITLE
Incredibly slow

### ISSUE THREAD

**Issue by Kebay** [matze/vim-tex-fold#6]
Sadly, at least on my system this is *way* to slow. If I edit the last lines of a file containing ~1000 files (and 130 `begin`s), I will get a huge lag.

**Comment by matze** [comment]
Although I don't have this problem even with similar sized files, I can imagine this being a problem on slower systems. However, there is not much I could do about it, because we have to do some regular expression matching in order to determine what kind of fold level we have. Your only other option is to disable the plugin and use manual folds (i..e. `%{{{` / `%}}}` pairs).
